### ISSUE TITLE
There's no send command in token moudle however return send_fee message by querying token's params

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#121]
## Summary of Bug
When I search the token moudle's params,return the send_fee message; but the token moudle no longer provides the send function

## Steps to Reproduce

command input:

```
1、okchaincli query token params


```
result ：

```
feeissue:
  denom: okt
  amount: "20000.00000000"
feemint:
  denom: okt
  amount: "2000.00000000"
feeburn:
  denom: okt
  amount: "10.00000000"
feemodify:
  denom: okt
  amount: "0.00000000"
feesend:
  denom: okt
  amount: "0.00000000"
feemultisend:
  denom: okt
  amount: "0.01000000"
feechown:
  denom: okt
  amount: "10.00000000"


```

## Version

v0.10.1

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
